### ISSUE TITLE
Issues directly after installation

### ISSUE THREAD

**Issue by SebT34** [XoopsModules25x/smallworld#10]
Hi, thanks for the job.
I have installed Smallworld in a new installation of xoops (2.5.11)
And i obtain that:
Error: Error: Class 'XoopsModules/Smallworld/User' not found in file /modules/smallworld/include/functions.php line 1342
Error: Error: Call to a member function getRequests() on null in file /modules/smallworld/include/functions.php line 1348
Error: Error: Class 'XoopsModules/Smallworld/User' not found in file /modules/smallworld/include/common.php line 41

I have commented these 3 lines and it's look like working. I will go deeper now 👍 Have a good day

**Comment by mambax7** [comment]
These changes should fix that: https://github.com/XoopsModules25x/smallworld/pull/11
