### ISSUE TITLE
Smallworld and Xoops 2.5.10

### ISSUE THREAD

**Issue by SebT34** [XoopsModules25x/smallworld#4]
Hi Culex, thanks for your great job. I ty to install Smallworld 1.16 with Xoops 2.5.10, but i obtain
 Error : Error: Class 'PublicWallUpdates' not found
Do you have any update about this module? Or an idea about how to solve this error?
Thanks by advance and thanks for your job in general. (Sorry for my english :)
Have a good day.
Sebastien

**Comment by zyspec** [comment]
Since we don't know exactly 'where' you saw the error - please post the exact error message (Debug mode  - 'Enable debug (inline debug)') in administration panel System Options -> Preferences -> General Settings

you might try adding
```require_once XOOPS_ROOT_PATH . '/modules/smallworld/class/publicWall.php';```
as the last line into ./class/class_collector.php to see if that fixes this particular problem

**Comment by SebT34** [comment]
Hi, thanks for your fast answer.

**I make a new installation of the module and:**

I have this error Before and after the installation:
0.000432 - SELECT userid, username FROM smallworld_user ORDER BY userid
Error number: 1146
Error message: Table 'dessinemtsebt_smallworld_user' doesn't exist

In phpmyadmin, the table exist, but still empty


**In Admin side after installation:**

0.000497 - ALTER TABLE smallworld_comments CHANGE 'comments' 'comments' TEXT
Error number: 1064
Error message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''comments' 'comments' TEXT' at line 1

JJDAI help me to fix it by changing in smallworld/index ligne 85

$Wall = ($profile >= 2) ? new smallworldWallUpdates() : new PublicWallUpdates();
replacing by
$Wall = ($profile >= 2) ? new smallworldWallUpdates() : new smallworldPublicWallUpdates();

and replace in smallworld/admin/upgrade.php ligne 65,  we have a "s" in comment.
$sql = 'ALTER TABLE ' . $xoopsDB->prefix('smallworld_comments') . " CHANGE 'comment' 'comment' TEXT;";

**And in User side:**
Error: Error: Class 'PublicWallUpdates' not found in file /modules/smallworld/index.php line 85

In the folder class, i have PublicWallUpdates.php but not publicwall.php. Where can i found it?
But i have ad
require_once XOOPS_ROOT_PATH . '/modules/smallworld/class/publicWallUpdate.php';

After all this change, i obtain a new error:
Unknown: __autoload() is deprecated, use spl_autoload_register() instead in file /class/mail/phpmailer/PHPMailerAutoload.php line 45
(I don't have a mail folder in class folder)

I hope this informations can help you.
Thanks a lot for your help. I hope i can use this perfect module in my site, he's doing exactly what i want:)

**Comment by zyspec** [comment]
It would help to know which version of XOOPS, PHP, and of Smallworld you are using to help you debug this further.

Just briefly looking through the Smallworld code there's several "installation" issues with this module.

1. The 1st time the module is installed, before the tables are inserted into the dB,  ./xoops_version.php tries to access the dB to build a HTML select box to allow restricting groups. Unfortunately this won't work since the tables aren't defined yet.  This code will need to be modified to check to see if the dB table exists prior to trying to access it.
2. Having a field in the SQL 'smallworld_comments' table the field named 'comment' is a bad idea. COMMENT is a reserved word in SQL. While techincally this should work - it's highly discouraged.  You are right that the issue in this case is the statement ```    $sql = 'ALTER TABLE ' . $xoopsDB->prefix('smallworld_comments') . " CHANGE 'comments' 'comments' TEXT";```  I haven't tried this but it looks to me like it should be changed to ``    $sql = 'ALTER TABLE ' . $xoopsDB->prefix('smallworld_comments') . " CHANGE 'comment' 'comment' TEXT";``` - the removal of the 's' in the column names.
3. The module is currently running the update script every time an admin page is loaded. This is a bad idea. The functionality included in the update script should be "moved" to ./include/onupdate.php so it is only run when the script is updated.
4. Not sure where you found the ./class/PublicWallUpdates.php file.  If you look at the current repository folder (https://github.com/XoopsModules25x/smallworld/tree/master/class) you'll see there is a ./class/publicWall.php that includes the Public_Wall_Updates class - but there is no seperate file named publicWallUpdates.php

I hope this helps you get further along.

**Comment by djculex** [comment]
Yeah I haven't really been good keeping this updated. I believe I wrote this for Xoops 2.5.7 and I havent had an eye on it since. I'll give it a spin with 2.5.10 and see what it does :-)

**Comment by mambax7** [comment]
I just uploaded some changes to my fork: https://github.com/mambax7/smallworld so you can go and try it. I focused on namespaces and on PHP 7
I did have some issues on the front-end with Javascript, and because I'm not an expert, there might be some issues to resolve...

**Comment by SebT34** [comment]
Hi. Thanks for your help. I will try and let you know. Thanks a lot to take time for me :)
Have a good night.

Not lot of time tonight, i will go more deeper tomorrow, but i already have an error

Error: Error: Class 'XoopsModules/Smallworld/Common/SysUtility' not found in file /modules/smallworld/class/Utility.php line 12


I have share with the french community [https://www.frxoops.org/modules/newbb/viewtopic.php?topic_id=38080&post_id=241404#forumpost241404](url)
Maybe some help from them too :)
Have a good night (from border between French Guiana and Brazil)

**Comment by djculex** [comment]
I have updated multible issues at least looks like it is running fine in my test server. 

When I wrote this the mysql did not give error when using reserved names in mysql like (comment, key etc) but now does. It should be ok now, Simply had to quote them `comment`.

I'll still keep checking to see if there are bugs

**Comment by SebT34** [comment]
Hi, thanks for your job. I'm back and start to work on my website again.
So with a fresh new installation of the last version (1.17), i have some issues in:
 **include/common.php:**

1)Warning: require_once(/modules/smallworld/include/../class/Helper.php): failed to open stream: No such file or directory in file /modules/smallworld/include/common.php line 24
**I comment the line**

2)Warning: require_once(/modules/smallworld/include/../class/Utility.php): failed to open stream: No such file or directory in file /modules/smallworld/include/common.php line 25
**I comment the line**

3)Error: Error: Class 'Xoopsmodules/smallworld/Helper' not found in file /modules/smallworld/include/common.php line 40
**I comment the line**

4)Error: Error: Class 'Xoopsmodules/smallworld/Utility' not found in file /modules/smallworld/include/common.php line 43
**I comment the line**

5)Notice: Undefined variable: helper in file /modules/smallworld/include/common.php line 56
Error: Error: Call to a member function loadLanguage() on null in file /modules/smallworld/include/common.php line 56
**I comment the line**

6)Notice: Undefined variable: helper in file /modules/smallworld/include/common.php line 60
Error: Error: Call to a member function getModule() on null in file /modules/smallworld/include/common.php line 60
**I comment the line**

7)Notice: Undefined variable: helper in file /modules/smallworld/include/common.php line 61
Error: Error: Call to a member function getModule() on null in file /modules/smallworld/include/common.php line 61
**I comment the line**

8)Notice: Undefined variable: pathModIcon16 in file /modules/smallworld/include/common.php line 74
Notice: Undefined variable: pathModIcon32 in file /modules/smallworld/include/common.php line 75
**I comment the line 74 and 75**

**and in smallworld/admin/admin_header.php:**

1)Notice: Undefined variable: helper in file /modules/smallworld/admin/admin_header.php line 39
Error: Error: Call to a member function isUserAdmin() on null in file /modules/smallworld/admin/admin_header.php line 39
**I comment the line:**
`/*if ($GLOBALS['xoopsUser'] instanceof \XoopsUser) {
    if (!$helper->isUserAdmin()) {
        $helper->redirect(XOOPS_URL . '/', 3, _NOPERM);
    }
} else {
    $helper->redirect(XOOPS_URL . '/user.php', 1, _NOPERM);
}
*/`

2)Notice: Undefined variable: helper in file /modules/smallworld/admin/admin_header.php line 56
Error: Error: Call to a member function getModule() on null in file /modules/smallworld/admin/admin_header.php line 56
**I comment the line:**

**Error 500
Go back to admin module and smallworld and:**

3)Comment line 60, 61, 62

**And in smallworld/admin/index.php**

1) Notice: Undefined variable: utility in file /modules/smallworld/admin/index.php line 37
Error: Error: Class name must be a valid object or a string in file /modules/smallworld/admin/index.php line 37
**I comment the line:**

2)Notice: Undefined variable: utility in file /modules/smallworld/admin/index.php line 209
Error: Error: Class name must be a valid object or a string in file /modules/smallworld/admin/index.php line 209
**I comment the line:**

And.. it's look like working fine. But some errors in debug:


Warning: count(): Parameter must be an array or an object that implements Countable in file /modules/smallworld/class/SmallWorldDB.php line 44
--
Warning: count(): Parameter must be an array or an object that implements Countable in file /modules/smallworld/class/SmallWorldDB.php line 74
Warning: getimagesize(https://www.sebt.fr/modules/smallworld/assets/images/genderless.png): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden in file /modules/smallworld/include/functions.php line 981
Warning: Division by zero in file /modules/smallworld/include/functions.php line 954
Warning: count(): Parameter must be an array or an object that implements Countable in file /modules/smallworld/class/SmallWorldDB.php line 101
Warning: getimagesize(https://www.sebt.fr/modules/smallworld/assets/images/genderless.png): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden in file /modules/smallworld/include/functions.php line 981
Warning: Division by zero in file /modules/smallworld/include/functions.php line 954

If my contribution can help :) Thanks a lot for the job. Really happy to can use it in my site.
Have a good day.

Sebastien

**Comment by djculex** [comment]
@SebT34 Yeah thats a big mess. I'm on it checking where did this go wrong.

A while ago I had this working but looks like I have misplaced this copy, but I'll see if I can't find it again :-)

**Comment by SebT34** [comment]
Now it's working fine. My website is in développement for the moment. He's doing exactly what i want, but no block for the moment. I try to make one 👍 I have searching everywhere a module doing that, and i didn't found it. Very thanks for your job. Have a good day. Sebastien

**Comment by djculex** [comment]
What do you want the block to do / show ??

**Comment by SebT34** [comment]
My website will be more a personal blog. I'm humanitarian, and my website give the possibility to my friends and family to follow me and keep contact)

I want to have access to smallworld on other page than Smallworld and website homepage. Same content but in one block? 

(And in my dream, i would have a block can show my wall only and not each user with his personnal wall.)
I hope my english is not to bad and you will understand my mind.

**Comment by djculex** [comment]
Ah I think I understand. But this block will be pretty big / wide to contain your posts, unless this is a buttom or top block. Hope I understand the idea.

**Comment by djculex** [comment]
With last update https://github.com/XoopsModules25x/smallworld/issues/4 should be fixed

**Comment by SebT34** [comment]
Hi Culex. Thanks a lot. I will try soon. Difficult in english for me to found thé good worlds, but thanks to all thé team working on it. I always found support, answer and good Spirit in thé xoops team👍😁

**Comment by djculex** [comment]
> 
> 
> Hi Culex. Thanks a lot. I will try soon. Difficult in english for me to found thé good worlds, but thanks to all thé team working on it. I always found support, answer and good Spirit in thé xoops team👍😁

Your are right though. This module need some blocks, originally I just thought the page would display all the features needed as hiding/showing layers, but as you say not all users has this as frontpage. I'm doing some house cleaning in the module now but hopefully I'll get a chance to modernize it a little and also include some blocks in the future.
